### PR TITLE
Firebase deployment

### LINKED ISSUE #35: Hosting online version of the project - Easy deployment
I'm trying to show this project to other people (medics, ...) and ease of running it is a problem. 
Some don't know/have a local server, so it's a blocker to give it a try! 
- maybe Numenta could host a page online for us
- I will try if the "Github pages" could do the work
- ???

### PR DESCRIPTION
**Pull request by rhyolight**
Fixes #35

### CODE REVIEW

**Comment by rhyolight** [comment]
@breznak @jefffohl See https://nupic-viz.firebaseapp.com/

**Comment by rhyolight** [comment]
Heroku is not the best for static file hosting.

**Comment by jefffohl** [comment]
Because Heroku will put the app to sleep after a certain amount of inactivity?

**Comment by breznak** [comment]
@rhyolight really cool, thanks! :sunglasses: Exactly what I've wanted. 
Btw, can we change the name to `nupic-visualizations` for now? To match with the proj. name. Is it really just a change to the `json`, no account needed?

**Comment by rhyolight** [comment]
https://nupic-visualizations.firebaseapp.com/

---

Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by breznak** [comment]
This will be great for presentations! :clap:

**Pull request merged**
