### PR TITLE
Check that last row is loaded completely

### LINKED ISSUE #61: Handle last row streaming file correctly
For #17 
- only for streaming file (a file that is being written to as is read by this app)
- the `chunk` can read an incomplete last row, 
  - which we use to create the `fieldMap` aka "headers for the graph"
    - so there can be columns missing!
- solve this by comparing lastRow to last-1 row
  - if their num columns differ, drop the last row

### PR DESCRIPTION
**Pull request by breznak**
Fixes #61 
@jefffohl please review if you have time

### CODE REVIEW

**Comment by jefffohl** [comment]
Thanks @breznak I will review today.

**Comment by jefffohl** [comment]
This looks good @breznak. Thanks! I noticed you made an additional commit recently. Are you done working on this?

**Comment by breznak** [comment]
Thanks @jefffohl , yes, this is the final form. I just noticed a simplification (the latest commit) on the way home. Good to merge then?

**Comment by jefffohl** [comment]
:+1: Looks good

**Pull request merged**
