### PR TITLE
Speedup rendering on huge graphs

### LINKED ISSUE #16: Rendering a large file (200k+) takes too long - rangeSelect, pan, ...
Working on real-life data, my files have something like 3M lines, even 280k lines file takes too long to open,zoom,pan, etc that it is not suitable for normal workflow. 

Can you replicate the problem, and if so, what can we do to overcome it? Optimizing the framework, or need to switch to some faster components? I was unable to debug which part is "freezing" the system, but assume it's the dygraph as the problem appeared when zooming a graph.

### PR DESCRIPTION
**Pull request by breznak**
Fixes #16 
- update Dygraphs & friends to the latest versions
- add CPU profiles in `examples/debug` (on Chromium v45, Ubuntu LTS, 64b)
- add large file (100k rows) to test in `examples/CSV`
- FIXed the extra slow zoom/rangeSelect in 4d945e6

### CODE REVIEW

**Comment by breznak** [comment]
@jefffohl please review, managed to fix this :smile: 
What needs to be done is updating the `build/` folder, I've changed the requirements, but mine installs to `./node_modules/`

**Comment by jefffohl** [comment]
Thanks @breznak I have some time today to get back into this. I will take a look at your PRs.

**Comment by breznak** [comment]
@jefffohl :+1: thanks

**Comment by jefffohl** [comment]
@breznak I am not sure what you mean by, "... mine installs to ./node_modules/"? Do you mean you are having a problem with using `gulp`?

Also, bower packages should be a part of the PR. In case you don't know - bower is a kind of package manager for web apps. In order to install your updated versions of bower packages, go to /client and run `bower install`. Then, commit your changes.

Usually, I include bower packages as part of a repo, because they are not specific to the developer's machine - but I do not include node_modules because those contain binaries meant to run only on the development environment.

**Comment by breznak** [comment]
@jefffohl 

> In order to install your updated versions of bower packages, go to /client and run bower install.

That was exactly my question. I think the dev. setup works for me, I follow the readme, run `npm install` and `gulp` in the `nupic.visualizations/` ..and stuff updates :wink: I was aware I need to actually commit the updated libs, but didn't know how to get them. Will do now. Should I also add `node_modules/` to .gitignore so it does not bother?

**Comment by breznak** [comment]
@jefffohl that should be it :+1:  Thanks for the advice!

**Comment by jefffohl** [comment]
@breznak This looks good, thanks! A couple of notes:
- What are the /examples/debug/ files for?
- It would be good to add some kind of user feedback after clicking the "Render" button. On huge files, there is a long pause, and we want the user to know that they should wait. I will make a new issue for that.

Feel free to merge the PR.

**Comment by breznak** [comment]
Thanks @jefffohl ! 
- `examples/debug` are CPU profiles from chromium, I used them to debug the speed issue. Maybe we can remove them later, but I think we'll use them (or newer) for handling really large files (1M+ points).

**Pull request merged**
