### PR TITLE
Addresses #56. Large files will be windowed - whether they are local or remote.

### PR DESCRIPTION
**Pull request by jefffohl**
Note that large remote files must be served from a server that supports CORS, because this feature requires streaming of the file.

### CODE REVIEW

**Comment by jefffohl** [comment]
@breznak - let me know if you would like to review this.

**Comment by breznak** [comment]
Hi @jefffohl ! I have reviewed it and looks all good :+1: 
Please merge as you see fit.

**Comment by breznak** [comment]
I'm merging to continue some work..

**Comment by jefffohl** [comment]
Thanks @breznak :+1:

**Pull request merged**
